//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_System_Water_C.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sistem_WalterEntities : DbContext
    {
        public Sistem_WalterEntities()
            : base("name=Sistem_WalterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Clientes> Tbl_Clientes { get; set; }
        public virtual DbSet<Tbl_ClientesNuevos> Tbl_ClientesNuevos { get; set; }
        public virtual DbSet<Tbl_Configuraciones> Tbl_Configuraciones { get; set; }
        public virtual DbSet<Tbl_Empleados> Tbl_Empleados { get; set; }
        public virtual DbSet<Tbl_Empresa> Tbl_Empresa { get; set; }
        public virtual DbSet<Tbl_Rol> Tbl_Rol { get; set; }
        public virtual DbSet<Tbl_Usuario> Tbl_Usuario { get; set; }
        public virtual DbSet<Tbl_Lectura> Tbl_Lectura { get; set; }
        public virtual DbSet<Tbl_Pago> Tbl_Pago { get; set; }
    }
}
