//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_System_Water_C.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Pago
    {
        public int Id_Pago { get; set; }
        public Nullable<int> Id_Cliente { get; set; }
        public Nullable<int> Id_Lectura { get; set; }
        public string Numero_Factura { get; set; }
        public Nullable<int> Lectura_Anterior { get; set; }
        public Nullable<int> Lectura_Actual { get; set; }
        public Nullable<int> Consumo { get; set; }
        public Nullable<decimal> Cuota_Fija { get; set; }
        public Nullable<decimal> Mes_Atrasado { get; set; }
        public Nullable<decimal> Mora { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> Fecha_Lectura { get; set; }
        public Nullable<System.DateTime> Fecha_Pago { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
    
        public virtual Tbl_Clientes Tbl_Clientes { get; set; }
        public virtual Tbl_Lectura Tbl_Lectura { get; set; }
    }
}
