//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_System_Water_C.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Usuario
    {
        public int Id_Usuarios { get; set; }
        public Nullable<int> Id_Nombre { get; set; }
        public string Usuario { get; set; }
        public string Contraseña { get; set; }
        public Nullable<int> Rol { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
    
        public virtual Tbl_Clientes Tbl_Clientes { get; set; }
        public virtual Tbl_Rol Tbl_Rol { get; set; }
    }
}
