//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_System_Water_C.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Configuraciones
    {
        public int Id_Configuracion { get; set; }
        public Nullable<decimal> Cuota_Fija { get; set; }
        public Nullable<decimal> Mora { get; set; }
        public Nullable<decimal> Valor_Metro { get; set; }
        public Nullable<decimal> Valor_Metro2 { get; set; }
        public Nullable<decimal> Valor_Metro3 { get; set; }
        public Nullable<decimal> Multas { get; set; }
        public string Detalles { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
    }
}
