//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_System_Water_C.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Empresa
    {
        public int Id_Empresa { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Correo { get; set; }
        public string NIT { get; set; }
        public string Rubro { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> Estado { get; set; }
        public string FechaRegistro { get; set; }
    }
}
