//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_System_Water_C.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ClientesNuevos
    {
        public int Id_Clientes_Nuevos { get; set; }
        public string Nombre { get; set; }
        public string Fecha_Inicio { get; set; }
        public Nullable<int> Monto_a_Pagar { get; set; }
        public Nullable<int> Plazo { get; set; }
        public Nullable<int> Cuota { get; set; }
        public string Estado { get; set; }
        public Nullable<int> EstadoConfig { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
        public Nullable<int> Estado2 { get; set; }
    }
}
