//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_System_Water_C.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Empleados
    {
        public int Id_Empleados { get; set; }
        public string Nombre_Completo { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Cargo { get; set; }
        public string DUI { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
    }
}
